sudo: required
services:
  - docker

before_install:
  - docker build -t hndrk/docker-react -f Dockerfile.dev .

script:
  - docker run hndrk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-844883607345"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $EB_ACCESS_KEY
  secret_access_key:
    secure: "$EB_SECRET_KEY"